/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp cn.kylinos.Kmre.Window.xml -i metatypes.h -a window_dbus
 *
 * qdbusxml2cpp is Copyright (C) 2023 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef WINDOW_DBUS_H
#define WINDOW_DBUS_H

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "metatypes.h"
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface cn.kylinos.Kmre.Window
 */
class WindowAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "cn.kylinos.Kmre.Window")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"cn.kylinos.Kmre.Window\">\n"
"    <method name=\"start\"/>\n"
"    <method name=\"launchApp\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"pkgName\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"width\"/>\n"
"      <arg direction=\"in\" type=\"i\" name=\"height\"/>\n"
"    </method>\n"
"    <method name=\"activeApp\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"pkgName\"/>\n"
"    </method>\n"
"    <method name=\"getRunningAppList\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"result\"/>\n"
"    </method>\n"
"    <method name=\"getAppMultipliers\">\n"
"      <arg direction=\"out\" type=\"s\" name=\"apps\"/>\n"
"    </method>\n"
"    <method name=\"answerCall\">\n"
"      <arg direction=\"in\" type=\"b\" name=\"accept\"/>\n"
"    </method>\n"
"    <signal name=\"containerEnvBooted\">\n"
"      <arg type=\"b\" name=\"status\"/>\n"
"      <arg type=\"s\" name=\"errInfo\"/>\n"
"    </signal>\n"
"    <signal name=\"updateAppStatus\">\n"
"      <arg type=\"s\" name=\"pkgName\"/>\n"
"      <arg type=\"i\" name=\"status\"/>\n"
"      <arg type=\"i\" name=\"type\"/>\n"
"    </signal>\n"
"    <signal name=\"syncFiles\">\n"
"      <arg type=\"i\" name=\"type\"/>\n"
"      <arg type=\"a(ss)\" name=\"metas\"/>\n"
"      <arg type=\"i\" name=\"totalNum\"/>\n"
"      <annotation value=\"AndroidMetaList\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
"    </signal>\n"
"    <signal name=\"postResponseInfo\">\n"
"      <arg type=\"i\" name=\"id\"/>\n"
"      <arg type=\"s\" name=\"pkgName\"/>\n"
"      <arg type=\"s\" name=\"category\"/>\n"
"      <arg type=\"i\" name=\"ret\"/>\n"
"      <arg type=\"s\" name=\"info\"/>\n"
"    </signal>\n"
"  </interface>\n"
        "")
public:
    WindowAdaptor(QObject *parent);
    virtual ~WindowAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void activeApp(const QString &pkgName);
    void answerCall(bool accept);
    QString getAppMultipliers();
    QString getRunningAppList();
    void launchApp(const QString &pkgName, int width, int height);
    void start();
Q_SIGNALS: // SIGNALS
    void containerEnvBooted(bool status, const QString &errInfo);
    void postResponseInfo(int id, const QString &pkgName, const QString &category, int ret, const QString &info);
    void syncFiles(int type, AndroidMetaList metas, int totalNum);
    void updateAppStatus(const QString &pkgName, int status, int type);
};

#endif
